### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by Zpadger** [soloice/Chinese-Character-Recognition#12]
你好，我在运行您的代码的时候出现报错：InvalidArgumentError (see above for traceback): Cannot assign a device to node 'InTopK': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: InTopK = InTopK[T=DT_INT64, k=3, _device="/device:GPU:0"](Softmax, label_batch)]]
我查了一下是GPU支持的问题，但是我看您的代码中allow_soft_placement参数已经设置为True。为什么还会有这个问题呢？请问如何解决？

**Comment by soloice** [comment]
呃，你先改成 CPU 试试？

**Comment by Zpadger** [comment]
你好，经过一天多的死磕bug[哭]，问题已解决，在不能使用GPU计算的代码段切换成CPU即可：        sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True,log_device_placement=True))
        sess.run(tf.global_variables_initializer())；在此特别感谢您的分享、帮助与指点！

**Comment by soloice** [comment]
恭喜恭喜！
