### ISSUE TITLE
Please give the directory

### ISSUE THREAD

**Issue by Zbeeee** [soloice/Chinese-Character-Recognition#13]
I want to know how to arrange the directory of the program and dataset.
My problem is that after showing "Training Starting", nothing was shown. So I think maybe my file directory is wrong.

**Comment by soloice** [comment]
project_directory/
---checkpoint/
---data/
------train/
---------xxx.jpg
------test/
---------yyy.jpg
---log/
---src/
------chinese_character_recognition_bn.py
