### ISSUE TITLE
Using this code to another dataset

### ISSUE THREAD

**Issue by Zbeeee** [soloice/Chinese-Character-Recognition#14]
你好，我用想把这个代码用到HWDB1.1 那个3926的数据集上可行吗? 就是在这个的汉字上加了一些符号。 我现在只是把charset_size改成了3926. 但是test accuracy 一直是0。请问应该如何解决呢？

**Comment by soloice** [comment]
理论上是只改一下 charset_size 就可以了。
好多人都说遇到了 test accuracy 为零的问题，我觉得可能是 TF 版本的问题（我写这个代码的时候 TF 还是 0.12 或者 1.0 rc）。我现在正在忙毕业，如果你不着急的话，过两周等我论文答辩完了检查一下……

**Comment by Zbeeee** [comment]
好的，谢谢。之前用你这个模型训练过汉字，现在人别人帮我再训一遍又是0了，所以可能是环境配置的问题。另外，有一个小小的问题，你是根据什么确定的网络结构呢？本人接触这方面时间不长，一直不太清楚网络的层数和一些参数是根据什么来确定的。比如之前知乎上那个文章的准确率比你这个低，但是你是怎么知道加完层数会提高表现呢？

**Comment by soloice** [comment]
网络结构没有黄金标准，都是试出来的。
不过一般来说参考主流模型就可以了，我这个模型主要是参考 VGG：小卷积核、多堆几层。
一般 MNIST 数字分类用三四层的网络很常见，汉字分类显然是比数字分类更难的任务，所以要多用一些卷积核、多堆几层。但是这个问题又不像 ImageNet 那么难，所以十几层可能也是没必要的（VGG 有 16 或 19 层），所以综合一下，可能六七层就差不多了。
当然我估计 10 层左右会更好，但是我当时也没有 GPU，网络太大的话训起来太慢，所以这个网络相对还是偏小。
