### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by Begeassgit** [soloice/Chinese-Character-Recognition#19]
When upgrade to Tensorflow2.0.0 and run this program(imported tensorflow.compat.v1 as tf), the 40th row has a problem:
absl.flags._exception.IllegalFlagValueError:flag --batch_size=128:('Non-boole an argument to boolean flag',128)

old code：
tf.app.flags.DEFINE_boolean('batch_size', 128, 'Validation batch size')

i think it should be:
tf.app.flags.DEFINE_integer('batch_size', 128, 'Validation batch size')

**Comment by soloice** [comment]
Haven't test it with TF 2, but you must be right.
