### ISSUE TITLE
My accuracy curve on the training set is similar as you provided, but my eval accuracy is so poor.

### ISSUE THREAD

**Issue by LittlePandaSea** [soloice/Chinese-Character-Recognition#5]
Thank you for your kind sharing of your code.
I have ran your code in my computer without change. 

It works well at first.
The training loss and accuracy curves on the training set are similar as you provided. 
But the eval accuracy after each 100 iterations is so poor that I wonder if I did something wrong.
Before 8000 iterations, the eval accuracy is always 0.

However,  it is lucky that the final results I got after 50000 iterations is top-1 91% and top 3 97%, very similar to your results. I just want to discuss about the possible reasons for this phenomenons.

1.  The similar performance in training set, but poor performance in test set in the first 10000 iterations.
2.  In order to get the same performance, why do I need much more iterations ?

But the way, when I try: `python chinese_character_recognition_bn.py --mode=validation`.  An error occurred.  
```
Traceback (most recent call last):
  File "chinese_character_recognition_bn.py", line 321, in <module>
    tf.app.run()
  File "/home/lpais/XYJgit/tensorflow/_python_build/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "chinese_character_recognition_bn.py", line 308, in main
    dct = validation()
  File "chinese_character_recognition_bn.py", line 233, in validation
    sess.run(tf.global_variables_initializer())
  File "/home/lpais/XYJgit/tensorflow/_python_build/tensorflow/python/client/session.py", line 769, in run
    run_metadata_ptr)
  File "/home/lpais/XYJgit/tensorflow/_python_build/tensorflow/python/client/session.py", line 967, in _run
    feed_dict_string, options, run_metadata)
  File "/home/lpais/XYJgit/tensorflow/_python_build/tensorflow/python/client/session.py", line 1017, in _do_run
    target_list, options, run_metadata)
  File "/home/lpais/XYJgit/tensorflow/_python_build/tensorflow/python/client/session.py", line 1037, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device to node 'InTopK': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: InTopK = InTopK[T=DT_INT64, k=3, _device="/device:GPU:0"](Softmax, label_batch)]]
Caused by op u'InTopK', defined at:
  File "chinese_character_recognition_bn.py", line 321, in <module>
    tf.app.run()
  File "/home/lpais/XYJgit/tensorflow/_python_build/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "chinese_character_recognition_bn.py", line 308, in main
    dct = validation()
  File "chinese_character_recognition_bn.py", line 230, in validation
    graph = build_graph(top_k=3)
  File "chinese_character_recognition_bn.py", line 133, in build_graph
    accuracy_in_top_k = tf.reduce_mean(tf.cast(tf.nn.in_top_k(probabilities, labels, top_k), tf.float32))
  File "/home/lpais/XYJgit/tensorflow/_python_build/tensorflow/python/ops/gen_nn_ops.py", line 1489, in in_top_k
    targets=targets, k=k, name=name)
  File "/home/lpais/XYJgit/tensorflow/_python_build/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/lpais/XYJgit/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/lpais/XYJgit/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device to node 'InTopK': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: InTopK = InTopK[T=DT_INT64, k=3, _device="/device:GPU:0"](Softmax, label_batch)]]
```

I have to remove the following code in the function build_graph(top_k) to run the validation :
(line 96)       `with tf.device(/gpu:0)`
It seems like some subfunctions in function of build_graph(top_k) are not  works in GPU devices.
When top_k = 1, it is ok, but if top_k = 3, I have to remove the code `with tf.device(/gpu:0)`.

Wish to get your reply! Thank you.

**Comment by soloice** [comment]
> poor performance in test set in the first 10000 iterations. In order to get the same performance, why I need much more iterations?

I don't know why this occurs to you.  Possible explanations include: different kernel implementation between CPU and GPU, different version of TensorFlow (I used tf 0.12 to produce these training curves. Maybe you are using tf 1.0 or an even later version), ...

However,` adjusting decay parameter of batch norm could be a remedy`.

Batch norm layers behave differently in training and testing phase. In training phase it utilizes statistics of the current batch, while using estimated population mean/variance in testing phase. The way to estimate population mean/variance is to maintain an exponential moving average of all batch statistics, i.e.: 
`new estimated statistics = decay * old estimated statistics + (1 - decay) * current batch statistics.` 

The effect is, if decay is too small (closer to 0.0), estimated statistics would be dominated by current batch statistics and could be unstable. On the other hand, if it is too large (closer to 1.0), it should be able to collect information from a longer history thus could be more stable, but the disadvantage is that it warms up very slow and needs to run for a longer time to establish a reasonable estimation of population mean/variance.

The default decay parameter of batch norm layer in slim is 0.999, sometimes which seems to be too conservative. You can specify a smaller value (maybe 0.995, 0.99 or 0.95) to see if it helps. You can set `normalizer_params={'is_training': is_training, 'decay': 0.99}` to achieve this.

> `tf.nn.in_top_k` failure on GPU.

I believe there's something wrong with the TensorFlow kernel, so it's better to create a minimal example and post such an issue on TensorFlow official repository. 

However, a workaround is: In TensorFlow, you can specify different devices for different ops. i.e.: you can keep other ops on GPU, while pinning `tf.nn.in_top_k` on CPU, to obtain faster inference speed.

**Comment by LittlePandaSea** [comment]
Thanks for your detailed and meaningful answers！
I will try to change the parameter your have mentioned.
Wish you have a nice day !

**Comment by soloice** [comment]
The same to you.

**Comment by soloice** [comment]
If smaller decay value works better, please let me know.
