### ISSUE TITLE
The GPU Utilization Rate is Zero!

### ISSUE THREAD

**Issue by LittlePandaSea** [soloice/Chinese-Character-Recognition#6]
Hi, soloice:
      I met a strange problem. At first, I cloned your code and downloaded the database  and the code worked very well. I got a quite high accuracy rate as you mentioned (Top-1>94%). But after a few days, I run the same code as usual, a strange phenomenon  has emerged. No matter training or validation, the running speed is much much slower! It seems like the GPU is not working. I use the order (nvidia -smi) to see what happened with GPU, and I find that the  GPU Utilization rate is also less than 5%, most time it is 0.
I do not know why. Because I have no change about the code or my hardware, and my other TensorFlow codes which is worked with GPU are still worked well.
And I try to copy the data and code to another place,(for example, the original code is on /xyj/test1/yourcode, and then I copy it to /xyj/documents/yourcode ), the same things happend.
At first, the code works well,  GPU Utilization rate is about that 70%. But after a few days, the same problem comes out. No matter training or validation, the running speed is much much slower! 
Do you know what happened? 
Wish you can give some suggestions.

**Comment by soloice** [comment]
Oops... This is wired.
I don't know, either.
Did you update your `TensorFlow` library during these days?

**Comment by LittlePandaSea** [comment]
No... But I think this is my own problem coupled with my specific devices or environments. I will try to solve it by myself in some ways. Thank you.

**Comment by soloice** [comment]
Good luck~
