### ISSUE TITLE
Using a 'tf.Tensor' as a Python 'bool' is not allowed.

### ISSUE THREAD

**Issue by chen11071402** [soloice/Chinese-Character-Recognition#9]
hello, I train this Chinese-Character-Recognition with the repo's dataset (tensorflow == gpu 1.2), but there are some problem with me：【TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.】
**#Can you tell me which version of tensorflow are you using? And what's the problem?**

**Comment by soloice** [comment]
Oops, I think this repo is based on tf 1.0.0-rc2.

**Comment by soloice** [comment]
I don't know which line raises this TypeError, but as the error suggestion says, you can use a tf.cond() to condition on a Tensor.

**Comment by chen11071402** [comment]
非常感谢你的回信！
   之前我是安装tf1.0.1版本的GPU，我的工作站配置是一个cpu至强的E5-2620v4和2个GTX1080ti。我是直接不改动运行你的程序，就也还不能正常运行，你的程序是否还需要改动哪里的吗？是在不行后又重装tf，造成系统崩溃了，不得不重装系统。
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Chong Ruan";<notifications@github.com>;
 发送时间: 2018年1月24日(星期三) 晚上9:56
 收件人: "soloice/Chinese-Character-Recognition"<Chinese-Character-Recognition@noreply.github.com>;
 抄送: "陈水标"<1255535910@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [soloice/Chinese-Character-Recognition] Using a 'tf.Tensor' as aPython 'bool' is not allowed. (#9)

 

 
I don't know which line raises this TypeError, but as the error suggestion says, you can use a tf.cond() to condition on a Tensor.
